project:
  type: website
  output-dir: .

website:
  title: "Krisna 'imed' Gupta"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - teaching.qmd
      - project.qmd
      - about.qmd

#bibliography: reference.bib
#nocite: |
#  @*
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



