project:
  type: website

website:
  title: "Website keren"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: metopel.qmd
        text: metopel
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



