project:
  type: website
  output-dir: .
  render:
    - "*.qmd"
    - "!aldi/"
    - "!latihanR/"
    - "!gravity/"


website:
  title: "Krisna 'imed' Gupta"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd
      - project.qmd
      - href: misc.qmd
        text: misc
        
      

#bibliography: reference.bib
#nocite: |
#  @*
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



