project:
  type: website
  output-dir: .

website:
  title: "Website keren"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: metopel.qmd
        text: metopel
      - about.qmd

bibliography: reference.bib
nocite: |
  @*
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



