---
title: "Projects"
---

## Work in Progress

### Working papers

- [The role of Indonesian nickel in the global market](https://www.researchgate.net/publication/389883484_KOMODITAS_NIKEL_INDONESIA_DAN_PERANANNYA_PADA_PASAR_GLOBAL) (in Bahasa Indonesia) with Theresia Anindita and Mas Rangga Cili.

- Surianta, A and Krisna Gupta. 2024. The effect of regional institutional quality on entrepreneurial flourishing in decentralized Indonesia. [Working paper](https://doi.org/10.13140/RG.2.2.30153.66408). 

- [Services and the third undbundling](/services/services_document.html) with Dhany Ratana. ERIA Book chapter

- The implication of the aggressive emission target on the Indonesian electricity sector.

- How important is Indonesian plastic waste import: an assessment on industry and the environment with Biyan Paramayuda.

- [The Assessment Of Competition, Markup, And Price Determination In The Indonesian Food And Beverage Industry](https://ideas.repec.org/p/idn/wpaper/wp032023.html) with Dionisius Narjoko and M. Ridhwan.

### Projects

- An OECD-related project with CIPS.

## Past project

### 2024

- Working with ADBI on measuring price elasticity of cigarettes excise.

### 2023

- Preparing a [policy brief](/aldi) for Ministry of Energy and Mineral Resource.

- Working with Prospera on measuring price elasticity of cigarettes excise.

- Working with Prospera on measuring the impact of import tax facility for firms.

### 2022

- Working with Prospera and CIPS on designing RCEP action plan.

- Working with CIPS for Katalis on measuring IA CEPA impacts.

- Working with PT. LAPI ITB for Indonesia Investment Authority on projecting the impact of INA to the Indonesian economy.