---
title: "A brief "
author: "Krisna Gupta"
institute: "Prospera"
date: last-modified
date-format: long
execute: 
  echo: false
  warning: false
abstract: "Policy brief"
format:
  html:
    code-fold: true
  pdf:
    documentclass: scrreprt
    papersize: a4
  docx:
    toc: false
---

okaowkaokwoak

```{r}
library(tidyverse)
library(ARDL)
library(vars)
library(readxl)
library(patchwork)
library(lubridate)
library(NasdaqDataLink)
#NasdaqDataLink.api_key("WKM7Rxc_WBWe1LYnHxR4")
NasdaqDataLink.api_key("vDm7zkSvztuywGuZuuvY")


```

```{r}

data1 <- NasdaqDataLink("FRED/DCOILWTICO",collapse="monthly", start_date="2019-01-01",order = "asc") |> rename(poil=Value)
data2 <- NasdaqDataLink("FRED/DFF",collapse="monthly", start_date="2019-01-01",order = "asc") |> rename(fedrate=Value)
data3 <- NasdaqDataLink("FRED/DGS10",collapse="monthly", start_date="2019-01-01",order = "asc") |> rename(b10=Value)
data4 <- NasdaqDataLink("FRED/DGS30",collapse="monthly", start_date="2019-01-01",order = "asc") |> rename(b30=Value)

data<-data1 |> left_join(data2) |> left_join(data3) |> left_join(data4)
data<-as_tibble(data)
dataa <- read_excel("aldi.xlsx",sheet="data")
dataa$Date<-as.Date(dataa$Date,format="%Y%m%d")
day(dataa$Date)<-days_in_month(dataa$Date)
dat<-left_join(data,dataa)
dat$bifr<-dat$bi-dat$fr
dat$q<-dat$q88+dat$q90+dat$q92+dat$q95
dat$p<-(dat$q88*dat$p88+dat$q90*dat$p90+dat$q92*dat$p92+dat$q95*dat$p98)/dat$q

```

```{r}

datl<-dat |>
  pivot_longer(!Date,names_to = "kind",values_to = "value")

a<-ggplot(subset(datl,kind %in% c("p88","p90","p92","p98","p95")),aes(x=Date,y=value,color=kind))+
  geom_line()+theme_classic()
b<-ggplot(subset(datl,kind %in% c("q88","q90","q92","q98","q95")),aes(x=Date,y=value,color=kind))+
  geom_line()+theme_classic()
a+b
```

```{r}
a<-ggplot(subset(datl,kind %in% c("fr")),aes(x=Date,y=value,color=kind))+
  geom_line()+theme_classic()
b<-ggplot(subset(datl,kind %in% c("poil")),aes(x=Date,y=value,color=kind))+
  geom_line()+theme_classic()
c<-ggplot(subset(datl,kind %in% c("q92")),aes(x=Date,y=value,color=kind))+
  geom_line()+theme_classic()
a/b/c
```

```{r}
VARselect(drop_na(dat[,c("p","poil","fr","xr")]))
```



